# Generated by Django 5.0.1 on 2024-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_customer_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('picture', models.ImageField(blank=True, default='avatar_customer.jpg', upload_to='customer')),
            ],
        ),
    ]
