# Generated by Django 5.0.1 on 2024-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
