# Generated by Django 5.0.1 on 2024-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_remove_customer_customer_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
