# Generated by Django 5.0.1 on 2024-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_customerprofile_user_driverprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
