# Generated by Django 5.0.1 on 2024-01-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_driverprofile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='day',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.driverprofile'),
        ),
    ]
