# Generated by Django 5.0.1 on 2024-01-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0013_rename_day_bookings_schedule_alter_bookings_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.customerprofile'),
        ),
    ]
