# Generated by Django 5.0.1 on 2024-01-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_alter_bookings_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='one.bookings'),
        ),
    ]
