# Generated by Django 5.0.1 on 2024-02-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0015_alter_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trans_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
